version: "3.0"

services:
  mongo:
    image: mongo:5
    ports:
      - "27017:27017"

  redis:
    image: redis:6
    ports:
      - '6379:6379'

  etcd:
    image: bitnami/etcd:3
    environment:
      ALLOW_NONE_AUTHENTICATION: yes
    ports:
      - "2379:2379"